version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:14.5-alpine
    env_file: ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    container_name: db

  
  web:
    #build: ./mafit/
    image: superprog/mafit-web:v1 
    env_file: .env
    restart: always
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db
    container_name: web
  

  gateway:
    #build: ./gateway/
    image: superprog/mafit-nginx:v1 
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/app/static/
      - media:/app/media/
    ports:
      - 8000:80 
    depends_on:
      - web
    container_name: gateway


  bot:
    #build: ./bot/
    image: superprog/mafit-bot:v1 
    env_file: .env
    restart: always
    volumes:
      - media:/app/media/
    links:
      - db
    container_name: bot
