# Generated by Django 4.2.6 on 2023-10-26 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_alter_userweight_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userweight',
            name='weight',
            field=models.FloatField(),
        ),
    ]
