# Generated by Django 4.2.6 on 2023-10-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_userweight_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='last_weight',
        ),
    ]
