# Generated by Django 4.2.6 on 2023-10-26 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_remove_user_last_weight'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workout',
            options={'default_related_name': 'exercises', 'ordering': ('-date',), 'verbose_name': 'Тренировка', 'verbose_name_plural': 'Тренировки'},
        ),
        migrations.AlterField(
            model_name='exercise',
            name='muscle',
            field=models.ForeignKey(default='-не указано', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='exercise', to='workouts.muscle'),
        ),
    ]
