# Generated by Django 4.2.6 on 2023-10-26 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_alter_workout_options_alter_exercise_muscle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise', to='workouts.muscle'),
        ),
    ]
