# Generated by Django 4.2.6 on 2023-10-26 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_alter_exercise_muscle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscle',
            field=models.ForeignKey(default='-не указано-', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='exercise', to='workouts.muscle'),
        ),
    ]
