# Generated by Django 4.2.6 on 2023-10-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_alter_exercise_muscle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='userweight',
            name='date',
            field=models.DateField(),
        ),
    ]
