# Generated by Django 4.2.6 on 2023-10-29 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_alter_history_date_alter_userweight_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userweight',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserWeight',
        ),
    ]
