# Generated by Django 4.2.6 on 2023-11-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_remove_history_exercise_remove_history_reps_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='exercise',
            field=models.ManyToManyField(help_text='Упражнение', through='workouts.HistoryExercise', to='workouts.exercise'),
        ),
    ]
