# Generated by Django 4.2.6 on 2023-11-15 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0013_history_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='history',
            name='workout',
        ),
        migrations.RemoveField(
            model_name='historyexercise',
            name='exercise',
        ),
        migrations.AddField(
            model_name='history',
            name='exercises',
            field=models.ManyToManyField(through='workouts.HistoryExercise', to='workouts.exercise'),
        ),
        migrations.AddField(
            model_name='historyexercise',
            name='exercises',
            field=models.ForeignKey(help_text='Упражнения', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HistoryExercise', to='workouts.exercise'),
        ),
        migrations.AlterField(
            model_name='history',
            name='author',
            field=models.ForeignKey(default=1, help_text='Автор записи', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historyexercise',
            name='history',
            field=models.ForeignKey(help_text='История', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HistoryExercise', to='workouts.history'),
        ),
    ]
