# Generated by Django 4.2.6 on 2023-11-30 17:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0014_remove_history_exercise_remove_history_workout_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='exercises',
        ),
        migrations.AddField(
            model_name='history',
            name='workout',
            field=models.ForeignKey(help_text='Связанная тренировка', null=True, on_delete=django.db.models.deletion.SET_NULL, to='workouts.workout'),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.date(2023, 11, 30), help_text='Дата тренировки'),
        ),
        migrations.AlterField(
            model_name='historyexercise',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historyexercise', to='workouts.history'),
        ),
    ]
