# Generated by Django 4.2.6 on 2023-12-26 19:29

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0016_alter_history_author_alter_history_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='comment',
            field=models.TextField(blank=True, help_text='Комментарий к тренировке', null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 26, 19, 29, 36, 905447, tzinfo=datetime.timezone.utc), help_text='Дата тренировки'),
        ),
        migrations.AlterField(
            model_name='historyexercise',
            name='history',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historyexercise', to='workouts.history'),
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='workouts.workout', verbose_name='Тренировка')),
            ],
            options={
                'verbose_name_plural': 'Избранные',
            },
        ),
        migrations.AddConstraint(
            model_name='favorites',
            constraint=models.UniqueConstraint(fields=('user', 'workout'), name='unique_combination'),
        ),
    ]
