# Generated by Django 4.2.6 on 2023-12-28 20:56

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0018_remove_workout_comment_history_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 12, 28, 20, 56, 12, 690520, tzinfo=datetime.timezone.utc), help_text='Дата тренировки'),
        ),
    ]
