# Generated by Django 4.2.6 on 2023-10-29 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('id',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterModelOptions(
            name='userweight',
            options={'default_related_name': 'weight', 'verbose_name': 'Вес пользователя', 'verbose_name_plural': 'Вес пользователей'},
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Эл.почта', max_length=100, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Никнейм', max_length=50, unique=True, verbose_name='Никнэйм'),
        ),
        migrations.AlterField(
            model_name='userweight',
            name='date',
            field=models.DateField(help_text='Дата'),
        ),
        migrations.AlterField(
            model_name='userweight',
            name='user',
            field=models.ForeignKey(default=1, help_text='Пользователь', on_delete=django.db.models.deletion.SET_DEFAULT, related_name='weight', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userweight',
            name='weight',
            field=models.FloatField(help_text='Вес в указазанную дату'),
        ),
    ]
