# Generated by Django 4.2.6 on 2023-12-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_userweight_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userweight',
            name='date',
        ),
        migrations.RemoveField(
            model_name='userweight',
            name='weight',
        ),
        migrations.AddField(
            model_name='userweight',
            name='photo',
            field=models.ImageField(default='static/img/profile.jpg', upload_to='media/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='userweight',
            name='purpose',
            field=models.FloatField(blank=True, help_text='Желаемый вес', null=True),
        ),
        migrations.AddField(
            model_name='userweight',
            name='weight_now',
            field=models.FloatField(blank=True, help_text='Текущий вес', null=True),
        ),
    ]
