# Generated by Django 4.2.6 on 2023-12-26 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userweight_date_remove_userweight_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userweight',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение'),
        ),
    ]
