# Generated by Django 4.2.6 on 2024-01-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_userweight_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userweight',
            name='purpose',
            field=models.FloatField(blank=True, default=0.0, help_text='Желаемый вес', null=True),
        ),
        migrations.AlterField(
            model_name='userweight',
            name='weight_now',
            field=models.FloatField(blank=True, default=0.0, help_text='Текущий вес', null=True),
        ),
    ]
