# Generated by Django 4.2.6 on 2024-01-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userweight_purpose_alter_userweight_weight_now'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userweight',
            options={},
        ),
        migrations.RemoveField(
            model_name='userweight',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='userweight',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='userweight',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userweight',
            name='weight_now',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_now',
            field=models.FloatField(blank=True, default=0.0, help_text='Текущий вес', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='weight_purpose',
            field=models.FloatField(blank=True, default=0.0, help_text='Желаемый вес', null=True),
        ),
    ]
