# Generated by Django 4.2.6 on 2024-01-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userweight_options_remove_userweight_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='weight_now',
            field=models.FloatField(blank=True, help_text='Текущий вес', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight_purpose',
            field=models.FloatField(blank=True, help_text='Желаемый вес', null=True),
        ),
    ]
