# Generated by Django 4.2.6 on 2024-01-18 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_weight_now_alter_user_weight_purpose'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWeight',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Никнэйм'),
        ),
    ]
